### PR TITLE
On OS X, we don't need .DS_Store files

### PR DESCRIPTION
**Pull request by ivanbportugal**
no .DS_Store files

### CODE REVIEW

**Comment by pepelsbey** [comment]
I'm sorry, but I don't need your BoltDB slides in the Shower template.

**Comment by ivanbportugal** [comment]
@pepelsbey That wasn't my intent... I opened this PR with just one file change (.gitignore). I didn't know that the PR got updated after the fact across repos...

I'll create a branch later and open a separate PR to show you what I'm talking about.

**Comment by pepelsbey** [comment]
I’d suggest adding all specific files you want to ignore to your global `.gitignore`, here’s mine:
```
$ cat .gitignore
*.pyc
.DS_Store
Desktop.ini
._*
Thumbs.db
.Spotlight-V100
.Trashes
```
Otherwise you’ll have to mention all `Thumbs.db` over and over again.

**Comment by tonyganch** [comment]
@ivanbportugal, I believe that platform and editor specific file types should be added to your personal global .gitignore, and not to project's source code.

**Comment by ivanbportugal** [comment]
I'm not sure I agree with the platform-specific stuff (I would have added Thumbs.db, etc...) but I can definitely see your point. No sweat and thanks for creating a nice project :)

**Pull request closed without merging**
