### PR TITLE
Mention DeckTape as an alternative for PDF printing

### PR DESCRIPTION
**Pull request by astefanutti**

### CODE REVIEW

**Comment by pepelsbey** [comment]
I’d love to feature another tool but it lacks some features and too complicated to install and use:

- No web fonts support (at least in Shower case)
- No multi-columns support (see updated [shwr.me](https://shwr.me/))
- Slides are printed in full mode, not in list mode, see inner navigation items, they should be fully revealed.
- It takes 4 complicated steps to install, not just `npm i -g decktape` (why not?)

**Comment by astefanutti** [comment]
Here is the latest version shwr.me exported as PDF with DeckTape: [test.pdf](https://github.com/shower/shower/files/311637/test.pdf)

> - No web fonts support (at least in Shower case)

That should work. I've tested it with the latest version of shwr.me on Mac OS X, see attached PDF.

> - No multi-columns support because of PhantomJS (see updated shwr.me)

I've just tested it with the latest version of shwr.me and that works fine, see attached PDF.

> - Slides are printed in full mode, not in list mode, see inner navigation items, they should be fully revealed.

Do you mean that the navigation items should not be exported one by one but rather once with the complete list? If yes, is there an API exposed by Shower? (there is astefanutti/decktape#24 related to that point in general).

> - It takes 4 complicated steps to install, not just npm i -g decktape (why not?)

Good idea. I'll work in it ASAP.

**Comment by pepelsbey** [comment]
> If yes, is there an API exposed by Shower?

There’s no specific API exposed by Shower, it’s even simpler. There are two modes:

- List mode
- Full mode

All features are split between two of them to make use of every feature in a proper moment. For example, `caption` and `badge` elements are hidden from the full mode but visible in the list mode. The same applies for inner navigation: in full mode you’re making it step by step, in list mode you have the final state right away.

Which brings us to another split: between media modes. Shower uses `screen` mode to split styles for slides only (available in all modes) and interface styles (available only in `screen` mode). So when you start printing Shower presenation you have only slides stacked one after another and nothing more — perfectly ready for pring, especially with:

```scss
@page {
	margin:0;
	size:$width $height;
	}
```

Do you expose `print` media mode while printing enabling Shower to show only needed parts?

**Comment by pepelsbey** [comment]
But with the latest PDF you printed I see it looks much better than before and and going to feature in documentation and in Twitter. Thank you for supporting Shower!

The only problem left is that you’re still printing every inner navigation step so there are five 11 slides in your PDF, but there should be only one, just like you have it when you print it using Chrome or Opera built-it PDF printer. It seems like you’re making it too complicated instead of just enabling `print` media mode and printing what’s in there accoring to `@print` directive.

**Comment by astefanutti** [comment]
Thanks a lot for the information. DeckTape does not currently set the `print` media mode as the majority of other HTML presentation frameworks tend to not play as well as Shower does with it 😉. This is possible to override the media type in QtWebKit, which PhantomJS uses, so I should find a way to make it set to `print` when the Shower plugin activates.

**Pull request closed without merging**
